In [1]:
from sklearn.ensemble import AdaBoostClassifier
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split,KFold,cross_val_score,GridSearchCV
from sklearn.datasets import load_iris

In [2]:
df = load_iris()
X = df.data
y = df.target
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=42)

In [4]:
abc = AdaBoostClassifier()
'''
Params
# base_estimator - The base estimator from which the boosted ensemble is built. If None, then the base estimator is DecisionTreeClassifier(max_depth=1)
# n_estimators default=50 The maximum number of estimators at which boosting is terminated. In case of perfect fit, 
                          the learning procedure is stopped early.
#learning_rate, default=1. Learning rate shrinks the contribution of each classifier by learning_rate. 
                           There is a trade-off between learning_rate and n_estimators.
'''
abc.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [6]:
print(abc.base_estimator_)
#print(abc.estimators_) #The collection of fitted sub-estimators.
print(abc.classes_)
print(abc.n_classes_)
print(abc.estimator_weights_)
print(abc.estimator_errors_)
print(abc.feature_importances_)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=1, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
[0 1 2]
3
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
[3.52380952e-01 8.10829312e-02 3.33356220e-01 1.27766428e-01
 3.33356697e-01 2.69089709e-04 3.33379342e-01 3.29312006e-04
 3.33366561e-01 3.75543246e-04 3.33378925e-01 3.50106968e-04
 3.33368643e-01 3.75221720e-04 3.33377356e-01 3.52991848e-04
 3.33369870e-01 3.71065458e-04 3.33376191e-01 3.54841729e-04
 3.33370761e-01 3.68100942e-04 3.33375358e-01 3.56351026e-04
 3.33371416e-01 3.66062510e-04 3.33374761e-01 

In [8]:
# Methods
print(abc.get_params())
print(abc.score(X_train,y_train))
print(abc.predict(X_train))
print(abc.predict_proba(X_train))

{'algorithm': 'SAMME.R', 'base_estimator': None, 'learning_rate': 1.0, 'n_estimators': 50, 'random_state': None}
0.9428571428571428
[1 1 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2 1 1 2 1 0 1 2 0
 0 1 2 0 2 0 0 2 1 2 1 1 2 1 0 0 1 2 0 0 0 1 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1
 1 1 0 1 1 0 1 2 2 0 1 2 1 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
[[4.50333201e-11 9.76564949e-01 2.34350509e-02]
 [5.05742009e-13 5.35891797e-01 4.64108203e-01]
 [3.07666472e-16 2.23042404e-02 9.77695760e-01]
 [4.50333201e-11 9.76564949e-01 2.34350509e-02]
 [3.07666472e-16 2.23042404e-02 9.77695760e-01]
 [4.50333201e-11 9.76564949e-01 2.34350509e-02]
 [3.07666472e-16 2.23042404e-02 9.77695760e-01]
 [4.50333201e-11 9.76564949e-01 2.34350509e-02]
 [9.99993027e-01 6.80956485e-06 1.63412069e-07]
 [3.07666472e-16 2.23042404e-02 9.77695760e-01]
 [4.50333201e-11 9.76564949e-01 2.34350509e-02]
 [9.99993027e-01 6.80956485e-06 1.63412069e-07]
 [9.99993027e-01 6.80956485e-06 1.63412069e-07]
 [9.99993027e-01 6.80956485e-0