In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split,KFold,cross_val_score,GridSearchCV
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB

In [2]:
df = load_iris()
X = df.data
y = df.target
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=42)

In [4]:
nb = GaussianNB()
'''
params

# priors : Prior probabilities of the classes. If specified the priors are not adjusted according to the data

'''
nb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [6]:
# Attributres

print(nb.class_count_) # No. of training samples observed in each class
print(nb.class_prior_) # Prob of each class
print(nb.classes_)
print(nb.sigma_) # variance of each feature per class #4 features and 3 classes so 3*4 matrix
print(nb.theta_)# mean of each feature per class

[31. 37. 37.]
[0.2952381  0.35238095 0.35238095]
[0 1 2]
[[0.1119667  0.13658689 0.03325703 0.01152966]
 [0.27532506 0.08724617 0.23934259 0.04134405]
 [0.42241052 0.09630387 0.28842951 0.08591673]]
[[4.96451613 3.37741935 1.46451613 0.2483871 ]
 [5.86216216 2.72432432 4.21081081 1.3027027 ]
 [6.55945946 2.98648649 5.54594595 2.00540541]]


In [8]:
# Methods
print(nb.get_params())
print(nb.score(X_train,y_train))
print(nb.predict(X_train))
print(nb.predict_proba(X_train))

{'priors': None, 'var_smoothing': 1e-09}
0.9428571428571428
[1 1 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2 1 1 2 1 0 1 2 0
 0 1 2 0 2 0 0 2 1 2 1 2 2 1 0 0 1 2 0 0 0 1 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1
 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 2 2 2 1 2 1 1 2 2 0 1 1 0 1 2]
(105, 3)
